import type { Metadata } from "next";
import { Geist } from "next/font/google";
import ThemeSwitcher from "@/components/theme-switcher";
import "./globals.css";
import type React from "react";
import { OnlineStatusToaster } from "@/components/offline-notification";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Lapusik Retail Accounting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={geistSans.className} lang="uk" suppressHydrationWarning>
      <body className="antialiased">
        <Providers>
          <ThemeSwitcher />
          {children}
          <Toaster position="top-right" richColors />
          <OnlineStatusToaster />
        </Providers>
      </body>
    </html>
  );
}
